version: 2.1

executors:
  default_executor:
    docker:
      - image: circleci/openjdk:8-jdk

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
  android_executor:
    docker:
      - image: circleci/android:api-29

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

commands:
  checkout_and_check_dependencies:
    description: "Checkout project and download dependencies"
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
  publish_to_maven_local:
    steps:
      - checkout_and_check_dependencies
      - run: ./gradlew clean publishToMavenLocal

jobs:
  build:
    executor: default_executor
    steps:
      - checkout_and_check_dependencies
      - run: ./gradlew clean assemble
  test:
    executor: default_executor
    steps:
      - run: echo $(ls -l)
      - checkout_and_check_dependencies
      - run: ./gradlew test
  test_app:
    executor: android_executor
    steps:
      - checkout_and_check_dependencies
      - publish_to_maven_local
      - run: cd test_app && ./gradlew test
  test_lib:
    executor: android_executor
    steps:
      - checkout_and_check_dependencies
      - publish_to_maven_local
      - run: cd test_app && ./gradlew test_lib:test
  check_deprecated_apis:
    executor: android_executor
    steps:
      - checkout_and_check_dependencies
      - publish_to_maven_local
      - run: test $(cd test_app && ./gradlew -Pandroid.debug.obsoleteApi=true | grep -c "com.sjcqs.android.config") = 0

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - test_app
      - test_lib
      - check_deprecated_apis